version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps: 
            - checkout 
            - run: 
                name: Install Deps
                command: bash ci.sh deps
            - run: 
                name: Build Toolchain
                command: timeout 120 bash build.sh || ls
                no_output_timeout: 240m
            - save_cache:
                key: v1-build
                paths:
                  - build
            - run: 
                name: Upload
                command: bash ci.sh upload
            
                    

