name: Build test
on:
  push:
    branches:
      - Linux
jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build Toolchain
      run: timeout 200 bash build.sh || bash ci.sh upload
    - name: Upload build 
      run: bash ci.sh upload
