name: Build test
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Upload build 
      run: bash ci.sh upload
